### ISSUE TITLE
可否加入不可触摸选择的开关，只能通过代码来设置是否选中。。。。

### ISSUE THREAD

**Issue by andansky** [andyxialm/SmoothCheckBox#3]

**Comment by andyxialm** [comment]
@andansky 感谢提issue
针对你说的这个问题，我个人觉得既然是CheckBox这种交互性的控件，点击默认存在我认为是合理的。暂时不会考虑加入不可点击的开关。

> 解决方案: 
如果确实有这种需求，你可以注释掉SmoothCheckBox控件中的相关代码：

> ```java
setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                toggle();
                mTickDrawing = false;
                mDrewDistance = 0;
                if (isChecked()) {
                    startCheckedAnimation();
                } else {
                    startUnCheckedAnimation();
                }
            }
        });
```
